server:
  port: 8000
  error:
    path: /error
    
application: 
  image:
    folder_path: classpath:assets/img
    
  email_verification:
    expires: 60
  security:
    jwt:
      secret_key: b1ad4d5b83cae5f7e11d7c2368e641c7bc7f6d65f9a4dfb593b663460fdd616d
      token_expires: 1
      refresh_token_expires: 60
spring:
  application:
    name: Aurora-QR-Code-base-Attendence-Management-System
  datasource:
    url: jdbc:h2:file:./src/main/resources/db/embdedded/h2
    driverClassName: org.h2.Driver
    username: sa
    password: sa
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: validate
    show-sql: true
  flyway:
    clean-disabled: false
    clean-on-validation-error: true
    baseline-on-migrate: true
  web:
    resources:
      static-locations:
        - classpath:assets

  mvc:
    static-path-pattern: /assets/**
    

    
    
    
    
  mail:
    port: 587
    host: smtp.gmail.com
    username: csibranch00@gmail.com
    password: eoyr dwhh kvro itur
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            
springdoc:
  show-actuator: true
  api-docs:
    enabled: true
  
